apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          command: ["/bin/sh", "-c"]
          args:
            - >
              if [ ! -d "/var/lib/kafka/data" ]; then
                echo "Formateando el directorio de datos de Kafka..."
                kafka-storage.sh format -t T5k_gA55Q6aE-C9n4J9fQ -c /etc/kafka/server.properties;
              fi;
              kafka-server-start.sh /etc/kafka/server.properties
          volumeMounts:
            - name: kafka-config-volume
              mountPath: /etc/kafka/server.properties
              subPath: server.properties
          env:
            - name: CLUSTER_ID
              value: "T5k_gA55Q6aE-C9n4J9fQ"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
      volumes:
        - name: kafka-config-volume
          configMap:
            name: kafka-config