apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${KUBE_APP_NAME}
  labels:
    app: ${KUBE_APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${KUBE_APP_NAME}
  template:
    metadata:
      labels:
        app: ${KUBE_APP_NAME}
    spec:
      containers:
        - name: ${KUBE_APP_NAME}
          image: ${IMAGE_NAME}
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CASSANDRA_USER
              valueFrom:
                secretKeyRef:
                  name: spring-boot-secrets
                  key: CASSANDRA_USER
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-boot-secrets
                  key: CASSANDRA_PASSWORD
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-boot-secrets
                  key: KAFKA_SASL_USERNAME
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-boot-secrets
                  key: KAFKA_SASL_PASSWORD