apiVersion: v1
kind: Service
metadata:
  name: ${KUBE_APP_NAME}-service
spec:
  type: ClusterIP
  selector:
    app: ${KUBE_APP_NAME}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081