apiVersion: v1
kind: Service
metadata:
  name: pipeline-crud
  #name: spring-boot-app  GITLAB
spec:
  type: ClusterIP
  selector:
    app: pipeline-crud
    #app: spring-boot-app GITLAB
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
