apiVersion: v1
kind: Service
metadata:
  name: ${{ env.APP_NAME }}
  #name: spring-boot-app  GITLAB
spec:
  type: ClusterIP
  selector:
    app: ${{ env.APP_NAME }}
    #app: spring-boot-app GITLAB
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
